// Code generated by "dbusutil-gen -type Job -output job_dbusutil.go job.go"; DO NOT EDIT.

package main

func (v *Job) setPropType(value string) (changed bool) {
	if v.Type != value {
		v.Type = value
		v.emitPropChangedType(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedType(value string) error {
	return v.service.EmitPropertyChanged(v, "Type", value)
}

func (v *Job) setPropStatus(value string) (changed bool) {
	if v.Status != value {
		v.Status = value
		v.emitPropChangedStatus(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedStatus(value string) error {
	return v.service.EmitPropertyChanged(v, "Status", value)
}

func (v *Job) setPropProgress(value float64) (changed bool) {
	if v.Progress != value {
		v.Progress = value
		v.emitPropChangedProgress(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedProgress(value float64) error {
	return v.service.EmitPropertyChanged(v, "Progress", value)
}

func (v *Job) setPropDescription(value string) (changed bool) {
	if v.Description != value {
		v.Description = value
		v.emitPropChangedDescription(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedDescription(value string) error {
	return v.service.EmitPropertyChanged(v, "Description", value)
}

func (v *Job) setPropSpeed(value int64) (changed bool) {
	if v.Speed != value {
		v.Speed = value
		v.emitPropChangedSpeed(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedSpeed(value int64) error {
	return v.service.EmitPropertyChanged(v, "Speed", value)
}

func (v *Job) setPropCancelable(value bool) (changed bool) {
	if v.Cancelable != value {
		v.Cancelable = value
		v.emitPropChangedCancelable(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedCancelable(value bool) error {
	return v.service.EmitPropertyChanged(v, "Cancelable", value)
}

func (v *Job) setPropDownloadSize(value int64) (changed bool) {
	if v.DownloadSize != value {
		v.DownloadSize = value
		v.emitPropChangedDownloadSize(value)
		return true
	}
	return false
}

func (v *Job) emitPropChangedDownloadSize(value int64) error {
	return v.service.EmitPropertyChanged(v, "DownloadSize", value)
}
