/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.AppStore.xml -a app_store_dbus_adapter -c AppStoreDBusAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "app_store_dbus_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AppStoreDBusAdapter
 */

AppStoreDBusAdapter::AppStoreDBusAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AppStoreDBusAdapter::~AppStoreDBusAdapter()
{
    // destructor
}

void AppStoreDBusAdapter::OpenApp(const QString &in0)
{
    // handle method call com.deepin.AppStore.OpenApp
    QMetaObject::invokeMethod(parent(), "OpenApp", Q_ARG(QString, in0));
}

void AppStoreDBusAdapter::Raise()
{
    // handle method call com.deepin.AppStore.Raise
    QMetaObject::invokeMethod(parent(), "Raise");
}

