/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.AppStore.xml -a app_store_dbus_adapter -c AppStoreDBusAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APP_STORE_DBUS_ADAPTER_H
#define APP_STORE_DBUS_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.AppStore
 */
class AppStoreDBusAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.AppStore")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.AppStore\">\n"
"    <method name=\"Raise\"/>\n"
"    <method name=\"OpenApp\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AppStoreDBusAdapter(QObject *parent);
    virtual ~AppStoreDBusAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void OpenApp(const QString &in0);
    void Raise();
Q_SIGNALS: // SIGNALS
};

#endif
