/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.AppStore.Metadata.xml -a app_store_metadata_dbus_adapter -i dbus/dbus_variant/app_metadata.h -c AppStoreMetadataDBusAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "app_store_metadata_dbus_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AppStoreMetadataDBusAdapter
 */

AppStoreMetadataDBusAdapter::AppStoreMetadataDBusAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AppStoreMetadataDBusAdapter::~AppStoreMetadataDBusAdapter()
{
    // destructor
}

QString AppStoreMetadataDBusAdapter::GetAppIcon(const QString &in0)
{
    // handle method call com.deepin.AppStore.GetAppIcon
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetAppIcon", Q_RETURN_ARG(QString, out0), Q_ARG(QString, in0));
    return out0;
}

AppMetadata AppStoreMetadataDBusAdapter::GetAppMetadata(const QString &in0)
{
    // handle method call com.deepin.AppStore.GetAppMetadata
    AppMetadata out0;
    QMetaObject::invokeMethod(parent(), "GetAppMetadata", Q_RETURN_ARG(AppMetadata, out0), Q_ARG(QString, in0));
    return out0;
}

void AppStoreMetadataDBusAdapter::OpenApp(const QString &in0)
{
    // handle method call com.deepin.AppStore.OpenApp
    QMetaObject::invokeMethod(parent(), "OpenApp", Q_ARG(QString, in0));
}

