/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.AppStore.Metadata.xml -a app_store_metadata_dbus_adapter -i dbus/dbus_variant/app_metadata.h -c AppStoreMetadataDBusAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APP_STORE_METADATA_DBUS_ADAPTER_H
#define APP_STORE_METADATA_DBUS_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus/dbus_variant/app_metadata.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.AppStore
 */
class AppStoreMetadataDBusAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.AppStore")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.AppStore\">\n"
"    <method name=\"OpenApp\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetAppMetadata\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"a(sss)\"/>\n"
"      <annotation value=\"AppMetadata\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"GetAppIcon\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AppStoreMetadataDBusAdapter(QObject *parent);
    virtual ~AppStoreMetadataDBusAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetAppIcon(const QString &in0);
    AppMetadata GetAppMetadata(const QString &in0);
    void OpenApp(const QString &in0);
Q_SIGNALS: // SIGNALS
};

#endif
